// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WUSTZone.Domain;

namespace WUSTZone.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220309020754_AddSeedPostTestData")]
    partial class AddSeedPostTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WUSTZone.Domain.Entityies.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FatherId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WUSTZone.Domain.Entityies.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Condensed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Category = 1,
                            CommentCount = 0,
                            Condensed = "",
                            Content = "郭森泽二号",
                            IsPinned = false,
                            IsSelected = false,
                            LikeCount = 0,
                            Photo = "",
                            TimeStamp = new DateTime(2022, 3, 9, 10, 7, 53, 729, DateTimeKind.Local).AddTicks(719),
                            Title = "",
                            UserId = 1
                        },
                        new
                        {
                            Id = 1002,
                            Category = 1,
                            CommentCount = 0,
                            Condensed = "",
                            Content = "郭森泽一号",
                            IsPinned = false,
                            IsSelected = false,
                            LikeCount = 0,
                            Photo = "",
                            TimeStamp = new DateTime(2022, 3, 9, 10, 7, 53, 731, DateTimeKind.Local).AddTicks(8180),
                            Title = "哈哈哈哈哈",
                            UserId = 0
                        },
                        new
                        {
                            Id = 1003,
                            Category = 3,
                            CommentCount = 0,
                            Condensed = "",
                            Content = "郭森泽三号",
                            IsPinned = false,
                            IsSelected = false,
                            LikeCount = 0,
                            Photo = "",
                            TimeStamp = new DateTime(2022, 3, 9, 10, 7, 53, 731, DateTimeKind.Local).AddTicks(8293),
                            Title = "",
                            UserId = 0
                        },
                        new
                        {
                            Id = 1004,
                            Category = 1,
                            CommentCount = 0,
                            Condensed = "",
                            Content = "郭森泽四号",
                            IsPinned = false,
                            IsSelected = false,
                            LikeCount = 0,
                            Photo = "",
                            TimeStamp = new DateTime(2022, 3, 9, 10, 7, 53, 731, DateTimeKind.Local).AddTicks(8296),
                            Title = "哈哈哈哈哈",
                            UserId = 0
                        },
                        new
                        {
                            Id = 1005,
                            Category = 1,
                            CommentCount = 0,
                            Condensed = "",
                            Content = "郭森泽五号",
                            IsPinned = false,
                            IsSelected = false,
                            LikeCount = 0,
                            Photo = "",
                            TimeStamp = new DateTime(2022, 3, 9, 10, 7, 53, 731, DateTimeKind.Local).AddTicks(8298),
                            Title = "哈哈哈哈哈",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("WUSTZone.Domain.Entityies.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
